const app=document.getElementById('app');
const nav=document.getElementById('nav');
let me=null;

const api=async(action,options={})=>{
  const r=await fetch('/api/index.js?action='+encodeURIComponent(action),{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  const text=await r.text();
  let data={};
  try{data=text?JSON.parse(text):{}}catch{data={error:'Resposta inválida do servidor.'}}
  if(!r.ok)throw new Error(data.error||'Erro interno.');
  return data;
};
const post=(action,data)=>api(action,{method:'POST',body:JSON.stringify(data)});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>{if(!d)return 'Data não informada';const s=String(d);const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return new Date(Date.UTC(+m[1],+m[2]-1,+m[3])).toLocaleDateString('pt-BR',{timeZone:'UTC'});const x=new Date(s);return Number.isNaN(x.getTime())?'Data não informada':x.toLocaleDateString('pt-BR')};
const fmtTime=t=>t?String(t).slice(0,5):'';
const photoOrInitial=(o,big=false)=>o.photo_url?`<img class="profilePhoto ${big?'big':''}" src="${o.photo_url}" alt="Foto de ${esc(o.nickname)}">`:`<div class="avatar ${big?'big':''}">${esc((o.nickname||'?').slice(0,2))}</div>`;
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),3500)}
function shell(){nav.innerHTML=`<a href="/visitantes">Visitante</a>${me?.role==='operator'?'<a href="/operador">Operador</a>':'<a href="/operador">Operador</a>'}${me?.role==='commander'?'<a href="/comandante">Comandante</a>':'<a href="/comandante">Comandante</a>'}${me?'<button class="ghost" id="logout">Sair</button>':'<a class="goldbtn small" href="/operador">Entrar</a>'}`;document.getElementById('logout')?.addEventListener('click',async()=>{await api('logout');location.href='/'});}

async function home(){
  const d=await api('public');
  app.innerHTML=`<section class="homeHero">
    <video class="heroVideo" autoplay muted loop playsinline poster="/logo.webp"><source src="/tga-home.mp4" type="video/mp4"></video>
    <div class="heroShade"></div>
    <div class="heroContent">
      <img class="heroLogo" src="/logo.webp" alt="Tactical Group Airsoft">
      <div class="eyebrow">TACTICAL GROUP AIRSOFT</div>
      <h1>Equipe. Hierarquia.<br><span>Operações.</span></h1>
      <p>Operação, treino e comunidade. Onde a disciplina do campo encontra a organização digital.</p>
      <div class="heroActions"><a class="goldbtn" href="/visitantes">Conhecer o time</a><a class="outlinebtn" href="/operador">Entrar</a></div>
    </div>
    <div class="heroCard"><b>PRÓXIMO JOGO</b>${d.games[0]?`<strong>${esc(d.games[0].title)}</strong><span>${fmt(d.games[0].game_date)}${d.games[0].game_time?' · '+fmtTime(d.games[0].game_time):''} · ${esc(d.games[0].location)}</span>`:'<span>Nenhum jogo publicado ainda.</span>'}</div>
  </section>
  <section class="homeInfo"><div class="infoCard"><img src="/logo.webp" alt="Logo Tactical Group Airsoft"><div><div class="eyebrow">PORTAL OFICIAL</div><h2>Disciplina, equipe e operação.</h2><p>Visitantes conhecem o time. Operadores cuidam do próprio perfil e presença. O comandante administra tudo.</p></div></div></section>`;
}

async function visitors(){
  const d=await api('public');
  const cards=d.operators.map(o=>`<a class="card operator visitorCard" href="/visitantes?operator=${o.id}">${photoOrInitial(o)}<div><h3>@${esc(o.nickname)}</h3><div class="rank">${esc(o.rank)}</div><p>${esc(o.function||'Operador')}</p><small>${o.airsoft_years?esc(o.airsoft_years)+' anos de airsoft':'Perfil em construção'}</small></div></a>`).join('');
  const q=new URLSearchParams(location.search);let profile='';
  if(q.get('operator')){
    try{
      const p=await api('operator&id='+q.get('operator')); const o=p.operator;
      profile=`<section class="profilePanel"><div class="profileHero">${photoOrInitial(o,true)}<div><div class="eyebrow">PERFIL DO OPERADOR</div><h2>@${esc(o.nickname)}</h2><div class="rank">${esc(o.rank)} · ${esc(o.function||'Operador')}</div><p>${esc(o.bio||'Sem descrição cadastrada.')}</p></div></div>
      <div class="profileStats"><div><b>Idade</b><span>${o.age?esc(o.age)+' anos':'Não informado'}</span></div><div><b>Airsoft</b><span>${o.airsoft_years?esc(o.airsoft_years)+' anos':'Não informado'}</span></div><div><b>Estilo</b><span>${esc(o.play_style||'Não informado')}</span></div><div><b>Jogos</b><span>${o.games_count||0}</span></div></div>
      <div class="profileCols"><div><h3>Loadout</h3><p><b>Principal:</b> ${esc(o.primary_replica||'Não informado')}</p><p><b>Secundária:</b> ${esc(o.secondary_replica||'Não informado')}</p><h3>Equipamentos</h3><div class="chips">${p.equipment.length?p.equipment.map(e=>`<span>${esc(e.name)}${e.details?' · '+esc(e.details):''}</span>`).join(''):'<span>Nenhum equipamento público.</span>'}</div></div><div><h3>Galeria</h3><div class="gallery">${p.gallery.length?p.gallery.map(g=>`<img src="${g.image_data}" alt="${esc(g.caption||'Foto do operador')}">`).join(''):'<div class="muted">Nenhuma foto cadastrada.</div>'}</div></div></div>
      <div class="profileActions"><a class="goldbtn" href="#visit">Solicitar visita</a><a class="outlinebtn" href="/visitantes">Voltar para operadores</a></div></section>`;
    }catch(e){profile=`<div class="error">${esc(e.message)}</div>`}
  }
  app.innerHTML=`<section><div class="pageTitle"><div class="pageBrand"><img src="/logo.webp" alt="Tactical Group Airsoft"><div><div class="eyebrow">ÁREA DO VISITANTE</div><h1>Conheça o time</h1><p>Veja patentes, funções, equipamentos e perfis públicos dos operadores.</p></div></div></div><div class="sectionHead"><div><div class="eyebrow">OPERADORES</div><h2>Equipe Tactical Group</h2></div><button id="visitBtn" class="goldbtn">Solicitar visita</button></div><div class="visitorGrid">${cards||'<div class="muted">Nenhum operador publicado.</div>'}</div>${profile}<div id="visit"></div></section>`;
  document.getElementById('visitBtn').onclick=visitorModal;
}
function visitorModal(){const m=document.createElement('div');m.className='modal';m.innerHTML=`<form class="modalBox"><button type="button" class="x">×</button><img class="accessLogo" src="/logo.webp"><div class="eyebrow">VISITANTE</div><h2>Solicitar visita</h2><input name="name" placeholder="Nome completo" required><input name="nickname" placeholder="Apelido"><input name="contact" placeholder="WhatsApp / contato" required><textarea name="message" placeholder="Mensagem para o comando"></textarea><button class="goldbtn">Enviar solicitação</button></form>`;document.body.appendChild(m);m.querySelector('.x').onclick=()=>m.remove();m.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const d=await post('visitor-request',Object.fromEntries(new FormData(e.target)));m.remove();toast(d.message)}catch(x){toast(x.message)}}}

function loginBox(mode='operator'){
  const label=mode==='commander'?'ENTRADA DO COMANDANTE':'ENTRADA DO OPERADOR';
  const title=mode==='commander'?'Comandante':'Operador';
  app.innerHTML=`<div class="auth"><form class="modalBox accessBox"><img class="accessLogo" src="/logo.webp" alt="Logo"><div class="eyebrow">${label}</div><h1>${title}</h1><div id="err"></div><input name="identifier" placeholder="E-mail ou apelido" required><input name="password" type="password" placeholder="Senha" required><button class="goldbtn">Entrar</button>${mode==='operator'?'<a class="outlinebtn" href="/operador/primeiro-acesso">Primeiro acesso com código</a>':''}<div class="accessLinks"><a href="/visitantes">Visitante</a><a href="/">Início</a></div></form></div>`;
  app.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const d=await post('login',Object.fromEntries(new FormData(e.target)));if(mode==='commander'&&d.user.role!=='commander')throw new Error('Esta conta não é de comandante.');if(mode==='operator'&&d.user.role!=='operator')throw new Error('Esta conta é de comandante. Entre pela área correta.');me=d.user;location.href=mode==='commander'?'/comandante':'/operador'}catch(x){document.getElementById('err').innerHTML=`<div class="error">${esc(x.message)}</div>`}}
}
function firstAccess(){app.innerHTML=`<div class="auth"><form class="modalBox accessBox"><img class="accessLogo" src="/logo.webp"><div class="eyebrow">PRIMEIRO ACESSO</div><h1>Ativar conta de operador</h1><div id="err"></div><input name="code" placeholder="Código TGA-XXXXXX-XXXXXX" required><input name="email" type="email" placeholder="Seu e-mail" required><input name="password" type="password" placeholder="Crie uma senha (mínimo 8 caracteres)" minlength="8" required><input name="confirm_password" type="password" placeholder="Confirme a senha" minlength="8" required><button class="goldbtn">Ativar minha conta</button><a class="outlinebtn" href="/operador">Já tenho conta</a></form></div>`;app.querySelector('form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(d.password!==d.confirm_password)return toast('As senhas não conferem.');delete d.confirm_password;try{const r=await post('activate-operator',d);me=r.user;toast('Conta ativada');setTimeout(()=>location.href='/operador',250)}catch(x){document.getElementById('err').innerHTML=`<div class="error">${esc(x.message)}</div>`}}}

async function operator(){
  const profile=await api('profile-data'); const d=await api('games'); const u=profile.user; const finance=d.finance;
  app.innerHTML=`<section><div class="pageTitle"><div class="pageBrand">${photoOrInitial(u,true)}<div><div class="eyebrow">ÁREA DO OPERADOR</div><h1>${esc(u.nickname)}</h1><p>Patente <b>${esc(u.rank)}</b> · ${u.absences||0} faltas${u.suspension_until?' · suspensão até '+fmt(u.suspension_until):''}</p></div></div></div>
  <div class="card operatorFinance ${finance?.status==='paid'||finance?.status==='waived'?'financeOk':'financePending'}"><div><div class="eyebrow">FINANCEIRO</div><h2>${finance?.status==='paid'?'Mensalidade em dia':finance?.status==='waived'?'Mensalidade isenta':finance?.status==='overdue'?'Mensalidade atrasada':'Mensalidade pendente'}</h2><p>${finance?`Valor: ${Number(finance.amount||0).toLocaleString('pt-BR',{style:'currency',currency:finance.currency||'BRL'})} · Vencimento ${fmt(finance.due_date)}`:'Nenhuma mensalidade configurada.'}</p></div><span class="tag">${finance?.status||'sem cobrança'}</span></div>
  <div class="operatorDashboard"><div class="card formCard"><div class="profileEditHead"><h2>Meu perfil</h2><span class="tag">Você edita</span></div><div class="uploadRow">${photoOrInitial(u,true)}<div><input id="photoInput" type="file" accept="image/*"><small>Até ~1,5 MB. Use uma foto quadrada ou retrato.</small></div></div><div class="formGrid"><input id="pfName" value="${esc(u.name||'')}" placeholder="Nome"><input id="pfEmail" value="${esc(u.email||'')}" placeholder="E-mail"><input id="pfAge" value="${esc(u.age||'')}" type="number" min="0" max="100" placeholder="Idade"><select id="pfBlood"><option value="">Tipo sanguíneo</option>${['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(x=>`<option ${u.blood_type===x?'selected':''}>${x}</option>`).join('')}</select><input id="pfYears" value="${esc(u.airsoft_years||'')}" type="number" min="0" max="80" step="0.5" placeholder="Anos de airsoft"><input id="pfStyle" value="${esc(u.play_style||'')}" placeholder="Estilo: Assault, Sniper, DMR..."><input id="pfPrimary" value="${esc(u.primary_replica||'')}" placeholder="Réplica principal"><input id="pfSecondary" value="${esc(u.secondary_replica||'')}" placeholder="Réplica secundária"><input id="pfFunction" value="${esc(u.function||'')}" placeholder="Função"><label class="checkline"><input id="pfPublic" type="checkbox" ${u.public_profile!==false?'checked':''}> Mostrar perfil para visitantes</label></div><textarea id="pfBio" placeholder="Descrição do operador">${esc(u.bio||'')}</textarea><textarea id="pfEquip" placeholder="Resumo de equipamentos">${esc(u.equipment_summary||'')}</textarea><button id="saveProfile" class="goldbtn">Salvar perfil</button></div>
  <div class="card"><div class="eyebrow">REGRAS</div><h2>Compromisso operacional</h2><p>Marcou <b>Vou</b>? Compareça. Faltas recorrentes podem levar a suspensão e perda de patente pelo comando.</p><div class="statsBox"><span><b>${u.games_count||0}</b> jogos</span><span><b>${u.absences||0}</b> faltas</span><span><b>${esc(u.elo||0)}</b> elo</span></div></div></div>
  <div class="operatorGrid"><div class="card"><h2>Equipamentos detalhados</h2><form id="equipForm" class="inlineForm"><select name="category"><option>Réplica</option><option>Secundária</option><option>Proteção</option><option>Rádio</option><option>Óptica</option><option>Vestimenta</option><option>Acessório</option></select><input name="name" placeholder="Ex.: Neptune 10" required><input name="details" placeholder="Detalhes"><button class="mini">Adicionar</button></form><div class="chipsList">${profile.equipment.map(e=>`<div class="chipRow"><span><b>${esc(e.category)}</b> · ${esc(e.name)}${e.details?' — '+esc(e.details):''}</span><button class="mini danger" data-del-equip="${e.id}">×</button></div>`).join('')||'<div class="muted">Nenhum equipamento detalhado.</div>'}</div></div><div class="card"><h2>Galeria de loadout</h2><div class="uploadGallery"><input id="galleryInput" type="file" accept="image/*"><input id="galleryCaption" placeholder="Legenda da foto"><button id="addGallery" class="mini">Adicionar foto</button></div><div class="gallery">${profile.gallery.map(g=>`<div class="galleryItem"><img src="${g.image_data}" alt="${esc(g.caption||'Foto')}"><div><small>${esc(g.caption||'')}</small><button class="mini danger" data-del-gallery="${g.id}">Excluir</button></div></div>`).join('')||'<div class="muted">Nenhuma foto cadastrada.</div>'}</div></div></div>
  <h2 class="sectionTitle">Próximos jogos</h2><div class="stack">${d.games.map(g=>`<article class="card game"><div><div class="date">${fmt(g.game_date)}${g.game_time?' · '+fmtTime(g.game_time):''}</div><h2>${esc(g.title)}</h2><p>${esc(g.location)}</p><p>${esc(g.description||g.notes||'Jogo confirmado pelo comando.')}</p>${g.briefing?`<p><b>Briefing:</b> ${esc(g.briefing)}</p>`:''}</div><div class="gameActions"><div class="choice"><button data-rsvp="going" data-id="${g.id}" class="${g.response==='going'?'selected':''}" ${finance?.status==='paid'||finance?.status==='waived'?'':'disabled'}>✓ Vou</button><button data-rsvp="not_going" data-id="${g.id}" class="${g.response==='not_going'?'selected no':''}">Não vou</button></div><div class="loadout"><b>LOADOUT DO JOGO</b><select data-role="${g.id}"><option value="">Função</option>${['Assault','Sniper','DMR','Suporte','Recon'].map(x=>`<option ${g.loadout?.funcao===x?'selected':''}>${x}</option>`).join('')}</select><input data-replica="${g.id}" value="${esc(g.loadout?.replica||'')}" placeholder="Réplica usada"><input data-note="${g.id}" value="${esc(g.loadout?.observacoes||'')}" placeholder="Observações"><button class="goldbtn small" data-save="${g.id}">Salvar loadout</button></div></div></article>`).join('')||'<div class="muted">Nenhum jogo próximo.</div>'}</div></section>`;
  const fileToDataURL=file=>new Promise((resolve,reject)=>{if(!file)return reject(new Error('Arquivo não selecionado.'));if(file.size>1_500_000)return reject(new Error('Use uma imagem de até 1,5 MB.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
  document.getElementById('saveProfile').onclick=async()=>{try{await post('update-profile',{name:document.getElementById('pfName').value,email:document.getElementById('pfEmail').value,age:document.getElementById('pfAge').value,blood_type:document.getElementById('pfBlood').value,airsoft_years:document.getElementById('pfYears').value,play_style:document.getElementById('pfStyle').value,primary_replica:document.getElementById('pfPrimary').value,secondary_replica:document.getElementById('pfSecondary').value,function:document.getElementById('pfFunction').value,bio:document.getElementById('pfBio').value,equipment_summary:document.getElementById('pfEquip').value,public_profile:document.getElementById('pfPublic').checked});toast('Perfil atualizado');location.reload()}catch(e){toast(e.message)}};
  document.getElementById('photoInput').onchange=async e=>{try{const data=await fileToDataURL(e.target.files[0]);await post('upload-photo',{image_data:data});toast('Foto de perfil atualizada');location.reload()}catch(x){toast(x.message)}};
  document.getElementById('addGallery').onclick=async()=>{try{const file=document.getElementById('galleryInput').files[0];const data=await fileToDataURL(file);await post('add-gallery',{image_data:data,caption:document.getElementById('galleryCaption').value});toast('Foto adicionada');location.reload()}catch(x){toast(x.message)}};
  app.querySelectorAll('[data-del-gallery]').forEach(b=>b.onclick=async()=>{await post('delete-gallery',{id:b.dataset.delGallery});location.reload()});app.querySelectorAll('[data-del-equip]').forEach(b=>b.onclick=async()=>{await post('delete-equipment',{id:b.dataset.delEquip});location.reload()});
  app.querySelector('#equipForm').onsubmit=async e=>{e.preventDefault();try{await post('equipment',Object.fromEntries(new FormData(e.target)));e.target.reset();location.reload()}catch(x){toast(x.message)}};
  app.querySelectorAll('[data-rsvp]').forEach(b=>b.onclick=async()=>{try{await post('rsvp',{game_id:b.dataset.id,response:b.dataset.rsvp});toast('Presença atualizada');operator()}catch(e){toast(e.message)}});
  app.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const id=b.dataset.save;try{await post('loadout',{game_id:id,loadout:{funcao:app.querySelector(`[data-role="${id}"]`).value,replica:app.querySelector(`[data-replica="${id}"]`).value,observacoes:app.querySelector(`[data-note="${id}"]`).value}});toast('Loadout salvo')}catch(e){toast(e.message)}})
}

async function financePanel(d){
  const settings=d.financeSettings||{monthly_fee:0,due_day:10,grace_days:0,currency:'BRL',active:true};
  const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:settings.currency||'BRL'});
  const current=(d.dues||[]);
  return `<section id="finance" class="financeSection"><div class="sectionHead compact"><div><div class="eyebrow">FINANCEIRO</div><h2>Mensalidades</h2><p class="muted">O operador só pode confirmar presença em jogos quando estiver em dia.</p></div></div><div class="financeStats"><div><b>${money(settings.monthly_fee)}</b><span>Mensalidade</span></div><div><b>Dia ${settings.due_day}</b><span>Vencimento</span></div><div><b>${current.filter(x=>x.status==='paid'||x.status==='waived').length}</b><span>Em dia</span></div><div><b>${current.filter(x=>x.status==='pending'||x.status==='overdue').length}</b><span>Pendentes</span></div></div><form id="financeSettingsForm" class="card financeSettings"><div class="cardKicker">CONFIGURAÇÕES</div><div class="formGrid"><input name="monthly_fee" type="number" step="0.01" min="0" value="${esc(settings.monthly_fee)}" placeholder="Valor mensal"><input name="due_day" type="number" min="1" max="28" value="${esc(settings.due_day)}" placeholder="Dia do vencimento"><input name="grace_days" type="number" min="0" max="30" value="${esc(settings.grace_days)}" placeholder="Dias de tolerância"><select name="currency"><option value="BRL" ${settings.currency==='BRL'?'selected':''}>BRL · Real</option><option value="USD" ${settings.currency==='USD'?'selected':''}>USD · Dólar</option></select></div><label class="checkline"><input name="active" type="checkbox" ${settings.active?'checked':''}> Exigir mensalidade para participação nos jogos</label><div class="heroActions"><button class="goldbtn">Salvar configurações</button><button type="button" id="generateDues" class="outlinebtn">Gerar mensalidades do mês</button></div></form><div class="card"><div class="table">${current.map(x=>`<div class="row financeRow"><div><b>@${esc(x.nickname)}</b><small>${esc(x.rank||'Operador')} · Vencimento ${fmt(x.due_date)}</small></div><span class="tag ${x.status==='paid'||x.status==='waived'?'paid':'pending'}">${x.status==='paid'?'PAGO':x.status==='waived'?'ISENTO':x.status==='overdue'?'ATRASADO':'PENDENTE'}</span><span>${money(x.amount)}</span><div class="financeActions"><button class="mini" data-pay="${x.operator_id}" data-period="${x.period}" data-amount="${x.amount}">Marcar pago</button><button class="mini danger" data-waive="${x.operator_id}" data-period="${x.period}" data-amount="${x.amount}">Isentar</button></div></div>`).join('')||'<p class="muted">Nenhuma mensalidade gerada.</p>'}</div></div></section>`;
}

async function commander(){
  const d=await api('commander');
  app.innerHTML=`<section><div class="pageTitle"><div class="pageBrand"><img src="/logo.webp" alt="Tactical Group Airsoft"><div><div class="eyebrow">COMANDO TGA</div><h1>Painel do Comandante</h1><p>Operações, operadores, patentes, presença, financeiro e disciplina.</p></div></div></div><div class="commandNav"><a href="#overview">Visão geral</a><a href="#games">Jogos</a><a href="#operators">Operadores</a><a href="#finance">Financeiro</a><a href="#visits">Visitas</a><a href="#settings">Configurações</a></div>
  <div id="overview" class="commandStats"><div><b>${d.games.length}</b><span>Jogos</span></div><div><b>${d.operators.filter(x=>x.role==='operator'&&x.active).length}</b><span>Operadores ativos</span></div><div><b>${d.operators.filter(x=>x.active===false).length}</b><span>Convites pendentes</span></div><div><b>${d.requests.filter(x=>x.status==='pending').length}</b><span>Visitas pendentes</span></div></div>
  <div id="games" class="adminGrid"><form id="gameForm" class="card formCard commanderGame"><div class="cardKicker">NOVA OPERAÇÃO</div><h2>Criar jogo</h2><div class="formGrid"><input name="title" placeholder="Nome da operação" required><input type="date" name="game_date" required><input type="time" name="game_time"><input name="location" placeholder="Local / campo" required><input type="number" name="max_players" min="1" placeholder="Limite de operadores"><select name="status"><option value="confirmado">Confirmado</option><option value="preparação">Em preparação</option><option value="cancelado">Cancelado</option></select></div><textarea name="description" placeholder="Resumo da operação"></textarea><textarea name="briefing" placeholder="Briefing para os operadores"></textarea><textarea name="notes" placeholder="Observações do comando"></textarea><button class="goldbtn">Publicar jogo</button></form>
  <form id="inviteForm" class="card formCard commanderInvite"><div class="cardKicker">NOVO OPERADOR</div><h2>Gerar convite</h2><p class="muted">Cadastre só o apelido e a função. O operador completa o restante do perfil no primeiro acesso.</p><input name="nickname" placeholder="Apelido" required><input name="function" placeholder="Função inicial · ex.: Assault"><button class="goldbtn">Gerar código de acesso</button><div id="inviteResult"></div></form></div>
  <div class="card"><div class="sectionHead compact"><div><div class="eyebrow">AGENDA</div><h2>Jogos programados</h2></div></div><div class="gameList">${d.games.map(g=>`<div class="commandGame"><div><b>${esc(g.title)}</b><small>${fmt(g.game_date)}${g.game_time?' · '+fmtTime(g.game_time):''} · ${esc(g.location)}</small></div><span class="tag">${esc(g.status||'confirmado')}</span><span>${g.going_count||0}/${g.participant_count||0} confirmados</span></div>`).join('')||'<div class="muted">Nenhum jogo cadastrado.</div>'}</div></div>
  <div id="operators" class="card"><div class="sectionHead compact"><div><div class="eyebrow">EQUIPE</div><h2>Operadores</h2></div></div><div class="table">${d.operators.map(o=>`<div class="row operatorAdminRow"><div><b>@${esc(o.nickname)}</b><small>${esc(o.function||'Operador')} · ${o.absences||0} falta(s)</small></div><span>${o.role==='commander'?'COMANDANTE':o.active?'ATIVO':'CONVITE'}</span>${o.active?`<select data-rank="${o.id}">${d.ranks.map(r=>`<option ${o.rank===r?'selected':''}>${r}</option>`).join('')}</select><span>${o.email?esc(o.email):'sem e-mail'}</span>${o.role==='operator'?`<button class="mini" data-penalty="${o.id}">Suspender 3 dias</button>`:''}`:`<span class="tag">${o.invite_expires_at?'expira '+fmt(o.invite_expires_at):'expirado'}</span><button class="mini danger" data-revoke="${o.id}">Revogar</button>`}</div>`).join('')}</div></div>
  <div id="visits" class="card"><div class="sectionHead compact"><div><div class="eyebrow">VISITAS</div><h2>Solicitações</h2></div></div>${d.requests.length?d.requests.map(r=>`<div class="visit"><div><b>${esc(r.name)}${r.nickname?' (@'+esc(r.nickname)+')':''}</b><p>${esc(r.contact)} · ${esc(r.message||'Sem mensagem')}</p></div><div class="visitActions">${r.status==='pending'?`<button class="mini" data-decision="approved" data-id="${r.id}">Aceitar</button><button class="mini danger" data-decision="rejected" data-id="${r.id}">Recusar</button>`:`<span class="tag">${esc(r.status)}</span>`}${r.status==='approved'?`<select data-visit="${r.id}"><option value="">Marcar em jogo...</option>${d.games.map(g=>`<option value="${g.id}">${esc(g.title)} · ${fmt(g.game_date)}</option>`).join('')}</select><button class="mini" data-assign="${r.id}">Marcar</button>`:''}</div></div>`).join(''):'<p class="muted">Nenhuma solicitação de visita.</p>'}</div>${await financePanel(d)}<div id="settings" class="card settingsNote"><div class="cardKicker">CONFIGURAÇÕES GERAIS</div><h2>Regras do comando</h2><p class="muted">Use as abas acima para navegar. A mensalidade é gerenciada em Financeiro e os demais controles permanecem no painel do comando.</p></div></section>`;
  app.querySelector('#gameForm').onsubmit=async e=>{e.preventDefault();try{await post('create-game',Object.fromEntries(new FormData(e.target)));toast('Jogo publicado');commander()}catch(x){toast(x.message)}};
  app.querySelector('#inviteForm').onsubmit=async e=>{e.preventDefault();try{const r=await post('create-invite',Object.fromEntries(new FormData(e.target)));document.getElementById('inviteResult').innerHTML=`<div class="inviteResult"><span>Código gerado</span><strong>${esc(r.code)}</strong><button type="button" id="copyInvite" class="mini">Copiar código</button><small>Entregue ao operador. O código expira em 24 horas e é usado uma única vez.</small></div>`;document.getElementById('copyInvite').onclick=async()=>{await navigator.clipboard?.writeText(r.code);toast('Código copiado')};e.target.reset()}catch(x){toast(x.message)}};
  app.querySelector('#financeSettingsForm').onsubmit=async e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(e.target));await post('finance-settings',{monthly_fee:b.monthly_fee,due_day:b.due_day,grace_days:b.grace_days,currency:b.currency,active:b.active==='on'});toast('Configurações financeiras salvas');commander()}catch(x){toast(x.message)}};
  app.querySelector('#generateDues').onclick=async()=>{try{await post('finance-generate',{});toast('Mensalidades do mês geradas');commander()}catch(x){toast(x.message)}};
  app.querySelectorAll('[data-pay]').forEach(b=>b.onclick=async()=>{try{await post('finance-payment',{operator_id:b.dataset.pay,period:b.dataset.period,amount:b.dataset.amount,status:'paid'});toast('Pagamento registrado');commander()}catch(x){toast(x.message)}});
  app.querySelectorAll('[data-waive]').forEach(b=>b.onclick=async()=>{try{await post('finance-payment',{operator_id:b.dataset.waive,period:b.dataset.period,amount:b.dataset.amount,status:'waived',note:'Isenção pelo comando'});toast('Mensalidade isentada');commander()}catch(x){toast(x.message)}});
  app.querySelectorAll('[data-rank]').forEach(s=>s.onchange=async()=>{try{await post('rank',{operator_id:s.dataset.rank,rank:s.value,reason:'Alteração pelo comando'});toast('Patente atualizada')}catch(e){toast(e.message)}});app.querySelectorAll('[data-penalty]').forEach(b=>b.onclick=async()=>{if(!confirm('Suspender este operador por 3 dias?'))return;try{await post('penalty',{operator_id:b.dataset.penalty,days:3,type:'suspensão',reason:'Disciplina'});toast('Suspensão aplicada');commander()}catch(e){toast(e.message)}});app.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{await post('revoke-invite',{operator_id:b.dataset.revoke});commander()});app.querySelectorAll('[data-decision]').forEach(b=>b.onclick=async()=>{await post('visitor-decision',{id:b.dataset.id,status:b.dataset.decision});commander()});app.querySelectorAll('[data-assign]').forEach(b=>b.onclick=async()=>{const game=app.querySelector(`[data-visit="${b.dataset.assign}"]`).value;if(!game)return toast('Escolha um jogo');await post('assign-visitor',{visitor_request_id:b.dataset.assign,game_id:game});toast('Visita marcada');commander()})
}

async function start(){
  if(location.pathname==='/operador/primeiro-acesso'){me=null;shell();return firstAccess()}
  if(location.pathname==='/operador' || location.pathname==='/comandante'){try{me=(await api('me')).user}catch{me=null}}else{try{me=(await api('me')).user}catch{me=null}}
  shell();
  try{if(location.pathname==='/visitantes')return await visitors();if(location.pathname==='/operador'){if(me?.role==='operator')return operator();return loginBox('operator')}if(location.pathname==='/comandante'){if(me?.role==='commander')return commander();return loginBox('commander')}return home()}catch(e){app.innerHTML=`<div class="error">${esc(e.message)}</div>`}
}
start();
