(()=>{
  if(location.pathname!=='/operador')return;
  const root=()=>document.getElementById('app');
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const date=d=>{if(!d)return 'Data não informada';const m=String(d).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:String(d)};
  const get=async url=>{const r=await fetch(url,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar dados');return d};
  const css=()=>{if(document.getElementById('operatorRescueCss'))return;const s=document.createElement('style');s.id='operatorRescueCss';s.textContent=`#operatorRescueTabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.operatorRescueTab{border:1px solid #30353b;background:#12161a;color:#d9dde1;border-radius:8px;padding:10px 16px;font:600 15px Rajdhani,sans-serif;cursor:pointer}.operatorRescueTab.active{background:#e3a51a;color:#101214}.operatorRescueGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.operatorRescueCard{border:1px solid #292e33;border-radius:10px;padding:16px;background:#111519}.operatorRescueCard img{width:72px;height:72px;border-radius:10px;object-fit:cover}.operatorRescueStats{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin:16px 0}.operatorRescueStat{border:1px solid #292e33;border-radius:9px;padding:13px;background:#0d1013}.operatorRescueStat b{display:block;font-size:22px}.operatorRescueGame{margin-top:12px}.operatorRescueGame h3{margin:0 0 6px}.operatorRescueLists{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:12px}.operatorRescueList{border:1px solid #292e33;border-radius:9px;padding:12px;background:#0d1013}.operatorRescueList a{display:block;padding:6px 0;color:inherit;text-decoration:none}.operatorRescueList a:hover{color:#e3a51a}@media(max-width:800px){.operatorRescueLists{grid-template-columns:1fr}}`;document.head.appendChild(s)};
  async function render(){
    css();
    let p,g,ops;
    try{[p,g,ops]=await Promise.all([get('/api/index.js?action=profile-data&_rescue='+Date.now()),get('/api/index.js?action=games&_rescue='+Date.now()),get('/api/index.js?action=public&_rescue='+Date.now())])}catch(e){const r=root();if(r)r.innerHTML=`<section class="panel"><div class="cardKicker">PAINEL DO OPERADOR</div><h1>Não foi possível carregar o painel</h1><div class="error">${esc(e.message)}</div><p class="muted">A sessão foi reconhecida, mas a API não conseguiu entregar os dados do operador.</p></section>`;return}
    const u=p.user||{};const games=g.games||[];const active=(ops.operators||[]).filter(o=>o.active!==false);
    const overview=`<section class="panel"><div class="cardKicker">ÁREA DO OPERADOR</div><div style="display:flex;gap:16px;align-items:center;flex-wrap:wrap"><img src="${esc(u.photo_url||'/logo.webp')}" style="width:92px;height:92px;border-radius:12px;object-fit:cover"><div><h1>@${esc(u.nickname||'Operador')}</h1>${u.name?`<p>${esc(u.name)}</p>`:''}<p class="muted">Patente: <b>${esc(u.rank||'Recruta')}</b> · Função: <b>${esc(u.function||'Operador')}</b></p></div></div><div class="operatorRescueStats"><div class="operatorRescueStat"><b>${esc(u.games_count||0)}</b><span>Jogos</span></div><div class="operatorRescueStat"><b>${esc(u.absences||0)}</b><span>Faltas</span></div><div class="operatorRescueStat"><b>${esc(u.elo_level||7)}/7</b><span>Elo</span></div><div class="operatorRescueStat"><b>${u.birth_date?date(u.birth_date):'—'}</b><span>Nascimento</span></div></div><div class="operatorRescueCard"><h2>Próximos jogos</h2>${games.length?games.slice(0,5).map(x=>`<div class="operatorRescueGame"><h3>${esc(x.title)}</h3><p>${date(x.game_date)}${x.game_time?' · '+esc(String(x.game_time).slice(0,5)):''} · ${esc(x.field_name||x.location||'Campo não informado')}</p></div>`).join(''):'<p class="muted">Nenhum jogo próximo.</p>'}</div></section>`;
    const team=`<section class="panel"><div class="cardKicker">EQUIPE</div><h1>Operadores ativos</h1><div class="operatorRescueGrid">${active.map(o=>`<a class="operatorRescueCard" href="/visitantes?operator=${encodeURIComponent(o.id)}&from=operator"><img src="${esc(o.photo_url||'/logo.webp')}"><h3>@${esc(o.nickname)}</h3><p>${esc(o.rank||'Operador')} · ${esc(o.function||'Operador')}</p></a>`).join('')||'<p class="muted">Nenhum operador ativo encontrado.</p>'}</div></section>`;
    const gameData=await get('/api/operator-games?_rescue='+Date.now()).catch(()=>({active:[],finished:[]}));
    const gameList=[...(gameData.active||[]).map(x=>({...x,_active:true})),...(gameData.finished||[]).map(x=>({...x,_active:false}))];
    const gamesPanel=`<section class="panel"><div class="cardKicker">JOGOS</div><h1>Jogos</h1><p class="muted">Jogos ativos e finalizados, com quem vai, quem não vai e presentes.</p>${gameList.length?gameList.map(x=>`<article class="operatorRescueCard operatorRescueGame"><h2>${esc(x.title)}</h2><p>${date(x.game_date)} · ${esc(x._active?'Ativo':'Finalizado')} · ${esc(x.field_name||x.field_address||'Campo não informado')}</p>${x._active?`<div class="operatorRescueLists"><div class="operatorRescueList"><b>🟢 Quem vai (${(x.going||[]).length})</b>${(x.going||[]).map(o=>`<a href="/visitantes?operator=${o.operator_id||o.id}&from=operator">@${esc(o.nickname)}</a>`).join('')||'<span class="muted">Nenhum</span>'}</div><div class="operatorRescueList"><b>🔴 Quem não vai (${(x.not_going||[]).length})</b>${(x.not_going||[]).map(o=>`<a href="/visitantes?operator=${o.operator_id||o.id}&from=operator">@${esc(o.nickname)}</a>`).join('')||'<span class="muted">Nenhum</span>'}</div><div class="operatorRescueList"><b>🟡 Sem resposta (${(x.pending||[]).length})</b>${(x.pending||[]).map(o=>`<a href="/visitantes?operator=${o.operator_id||o.id}&from=operator">@${esc(o.nickname)}</a>`).join('')||'<span class="muted">Nenhum</span>'}</div></div>`:`<div class="operatorRescueList"><b>Operadores presentes (${(x.present||[]).length})</b>${(x.present||[]).map(o=>`<a href="/visitantes?operator=${o.operator_id||o.id}&from=operator">@${esc(o.nickname)}</a>`).join('')||'<span class="muted">Nenhum registro</span>'}</div>`}</article>`).join(''):'<div class="operatorRescueCard"><p class="muted">Nenhum jogo encontrado.</p></div>'}</section>`;
    const r=root();if(!r)return;r.innerHTML='<div id="operatorRescueTabs"><button class="operatorRescueTab active" data-r="overview">Visão geral</button><button class="operatorRescueTab" data-r="team">Operadores ativos</button><button class="operatorRescueTab" data-r="games">Jogos</button></div><div id="operatorRescueContent"></div>';
    const c=document.getElementById('operatorRescueContent');const show=k=>{c.innerHTML=k==='overview'?overview:k==='team'?team:gamesPanel;r.querySelectorAll('[data-r]').forEach(b=>b.classList.toggle('active',b.dataset.r===k))};
    r.querySelector('[data-r="overview"]').onclick=()=>show('overview');r.querySelector('[data-r="team"]').onclick=()=>show('team');r.querySelector('[data-r="games"]').onclick=()=>show('games');show('overview');
  }
  const rescue=()=>{const r=root();if(!r)return;const t=(r.textContent||'').trim();if(t==='Carregando...'||t.includes('Sua sessão está ativa. O painel principal está sendo atualizado.'))render()};
  setTimeout(rescue,1300);setTimeout(rescue,2500);setTimeout(rescue,4500);
})();