import { neon } from '@neondatabase/serverless'
import bcrypt from 'bcryptjs'
import crypto from 'node:crypto'

const sql=neon(process.env.DATABASE_URL)
const COOKIE='tg_session'
const ranks=['Recruta','Soldado','Cabo','3º Sargento','2º Sargento','1º Sargento','Subtenente','Aspirante','Tenente','Capitão','Major','Tenente-Coronel','Coronel']
const json=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store,max-age=0');res.end(JSON.stringify(data))}
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>{const i=v.indexOf('=');return [v.slice(0,i).trim(),decodeURIComponent(v.slice(i+1))]}))
const hash=t=>crypto.createHash('sha256').update(t).digest('hex')
const publicRow=o=>({id:o.id,name:o.name,nickname:o.nickname,rank:o.rank,function:o.function||'Operador',games_count:o.games_count||0,absences:o.absences||0,photo_url:o.photo_url||null,bio:o.bio||'',equipment_summary:o.equipment_summary||'',elo:o.elo||0,elo_level:Math.min(7,Math.max(1,Number(o.elo_level)||7)),age:o.age||null,birth_date:o.birth_date||null,blood_type:o.blood_type||null,airsoft_years:o.airsoft_years||null,play_style:o.play_style||'',primary_replica:o.primary_replica||'',secondary_replica:o.secondary_replica||''})
async function user(req){const token=cookies(req)[COOKIE];if(!token)return null;const rows=await sql`SELECT o.* FROM sessions s JOIN operators o ON o.id=s.operator_id WHERE s.token_hash=${hash(token)} AND s.expires_at>now() AND o.active=true LIMIT 1`;return rows[0]||null}
async function requireUser(req,res,role){const u=await user(req);if(!u){json(res,401,{error:'Faça login.'});return null}if(role==='operator'&&!['operator','commander'].includes(u.role)){json(res,403,{error:'Acesso restrito.'});return null}if(role==='commander'&&u.role!=='commander'){json(res,403,{error:'Acesso restrito.'});return null}return u}
async function settings(){return (await sql`SELECT * FROM finance_settings WHERE id=1 LIMIT 1`)[0]||{instagram_url:null,pix_key:null,pix_holder:null,currency:'BRL',active:true}}
export default async function handler(req,res){try{const url=new URL(req.url,'http://localhost');const action=url.searchParams.get('action')||'public';if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}
if(action==='login'&&req.method==='POST'){let raw='';for await(const c of req)raw+=c;const b=JSON.parse(raw||'{}');const identifier=String(b.identifier||'').trim().toLowerCase();const pass=String(b.password||'');const rows=await sql`SELECT * FROM operators WHERE active=true AND (lower(coalesce(email,''))=${identifier} OR lower(nickname)=${identifier}) LIMIT 1`;const u=rows[0];if(!u||!(await bcrypt.compare(pass,u.password_hash)))return json(res,401,{error:'E-mail/apelido ou senha inválidos.'});if(u.suspension_until&&new Date(u.suspension_until)>new Date())return json(res,403,{error:`Conta suspensa até ${new Date(u.suspension_until).toLocaleDateString('pt-BR')}.`});const token=crypto.randomBytes(32).toString('hex');await sql`INSERT INTO sessions(token_hash,operator_id,expires_at) VALUES(${hash(token)},${u.id},now()+interval '14 days')`;res.setHeader('Set-Cookie',`${COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=${60*60*24*14}`);return json(res,200,{user:{id:u.id,name:u.name,nickname:u.nickname,email:u.email||null,role:u.role,rank:u.rank,function:u.function||null,bio:u.bio||null,absences:u.absences||0,suspension_until:u.suspension_until||null}})}
if(action==='me'){const u=await user(req);return json(res,200,{user:u?{id:u.id,name:u.name,nickname:u.nickname,email:u.email||null,role:u.role,is_primary_commander:!!u.is_primary_commander,rank:u.rank,function:u.function||null,bio:u.bio||null,absences:u.absences||0,suspension_until:u.suspension_until||null,age:u.age||null,blood_type:u.blood_type||null,airsoft_years:u.airsoft_years||null,play_style:u.play_style||'',primary_replica:u.primary_replica||'',secondary_replica:u.secondary_replica||'',birth_date:u.birth_date||null,equipment_summary:u.equipment_summary||'',photo_url:u.photo_url||null,public_profile:u.public_profile}:null})}
if(action==='logout'){const token=cookies(req)[COOKIE];if(token)await sql`DELETE FROM sessions WHERE token_hash=${hash(token)}`;res.setHeader('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0`);return json(res,200,{ok:true})}
if(action==='push-config')return json(res,200,{enabled:!!(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT),publicKey:process.env.VAPID_PUBLIC_KEY||null})
if(action==='notifications'){const u=await requireUser(req,res);if(!u)return;return json(res,200,{items:await sql`SELECT * FROM notifications WHERE operator_id=${u.id} ORDER BY created_at DESC LIMIT 30`})}
if(action==='profile-data'){const u=await requireUser(req,res,'operator');if(!u)return;const equipment=await sql`SELECT id,category,name,details,public_visible,photo_url FROM operator_equipment WHERE operator_id=${u.id} ORDER BY category,name`;const gallery=await sql`SELECT id,image_data,caption,created_at FROM operator_gallery WHERE operator_id=${u.id} ORDER BY created_at DESC LIMIT 30`;const guardianOptions=await sql`SELECT id,name,nickname,rank,function,role,photo_url FROM operators WHERE active=true AND id<>${u.id} ORDER BY CASE WHEN role='commander' THEN 0 ELSE 1 END,nickname`;const guardian=u.guardian_operator_id?(await sql`SELECT id,name,nickname,rank,function,role,photo_url FROM operators WHERE id=${u.guardian_operator_id} AND active=true LIMIT 1`)[0]||null:null;return json(res,200,{user:u,equipment,gallery,guardian,guardianOptions})}
if(action==='team-members'){const u=await requireUser(req,res,'operator');if(!u)return;const ops=await sql`SELECT id,name,nickname,role,rank,function,games_count,absences,photo_url,bio,public_profile,elo_level FROM operators WHERE active=true ORDER BY CASE WHEN role='commander' THEN 0 ELSE 1 END,nickname`;const s=await settings();return json(res,200,{operators:ops.map(publicRow),instagram_url:s.instagram_url||null})}
if(action==='public'){const ops=await sql`SELECT * FROM operators WHERE active=true AND public_profile=true ORDER BY CASE WHEN role='commander' THEN 0 ELSE 1 END,nickname`;const games=await sql`SELECT g.id,g.title,g.game_date,g.game_time,g.location,g.status,g.description,g.notes,g.briefing,g.max_players,g.min_players,g.rsvp_deadline_date,g.rsvp_deadline_time,gf.name field_name,gf.maps_url field_maps_url,COALESCE((SELECT json_agg(json_build_object('id',o.id,'nickname',o.nickname,'rank',o.rank,'function',o.function,'photo_url',o.photo_url,'loadout',gp.loadout) ORDER BY o.nickname) FROM game_participants gp JOIN operators o ON o.id=gp.operator_id WHERE gp.game_id=g.id AND gp.response='going' AND o.active=true),'[]'::json) participants FROM games g LEFT JOIN game_fields gf ON gf.id=g.field_id WHERE g.game_date>=CURRENT_DATE AND COALESCE(g.status,'')<>'cancelado' ORDER BY g.game_date,g.game_time NULLS LAST LIMIT 20`;const s=await settings();const completedGames=await sql`SELECT id,title,game_date,game_time,location,status,match_photo_url,completed_at FROM games WHERE status='finalizado' ORDER BY game_date DESC,game_time DESC NULLS LAST LIMIT 50`;return json(res,200,{operators:ops.map(publicRow),games,completedGames,ranks,instagram_url:s.instagram_url||null})}
if(action==='operator'){const id=url.searchParams.get('id');if(!id)return json(res,400,{error:'Operador não informado.'});const op=(await sql`SELECT * FROM operators WHERE id=${id} AND active=true AND public_profile=true LIMIT 1`)[0];if(!op)return json(res,404,{error:'Operador não encontrado.'});const equipment=await sql`SELECT id,category,name,details,public_visible,photo_url FROM operator_equipment WHERE operator_id=${id} AND public_visible=true ORDER BY category,name`;const gallery=await sql`SELECT id,image_data,caption,created_at FROM operator_gallery WHERE operator_id=${id} ORDER BY created_at DESC LIMIT 18`;const guardian=op.guardian_operator_id?(await sql`SELECT id,name,nickname,rank,function,role,photo_url FROM operators WHERE id=${op.guardian_operator_id} AND active=true LIMIT 1`)[0]||null:null;const responsibleFor=await sql`SELECT id,name,nickname,rank,function,photo_url FROM operators WHERE guardian_operator_id=${id} AND active=true ORDER BY nickname`;return json(res,200,{operator:{...publicRow(op),is_minor:Boolean(op.guardian_operator_id),guardian:guardian?publicRow(guardian):null,responsible_for:responsibleFor.map(publicRow)},equipment,gallery})}
if(action==='games'){const u=await requireUser(req,res);if(!u)return;const games=await sql`SELECT g.*,gf.name field_name,gf.address field_address,gf.maps_url field_maps_url,COALESCE(gp.response,'pending') response,gp.loadout,gp.responded_at,COALESCE((SELECT count(*)::int FROM game_participants q WHERE q.game_id=g.id AND q.response='going'),0) going_count,COALESCE((SELECT json_agg(json_build_object('id',o.id,'nickname',o.nickname,'rank',o.rank,'function',o.function,'photo_url',o.photo_url,'elo_level',o.elo_level,'loadout',q.loadout) ORDER BY o.nickname) FROM game_participants q JOIN operators o ON o.id=q.operator_id WHERE q.game_id=g.id AND q.response='going' AND o.active=true),'[]'::json) participants,COALESCE((SELECT json_agg(json_build_object('id',o.id,'nickname',o.nickname,'rank',o.rank,'function',o.function,'photo_url',o.photo_url,'elo_level',o.elo_level,'loadout',q.loadout) ORDER BY o.nickname) FROM game_participants q JOIN operators o ON o.id=q.operator_id WHERE q.game_id=g.id AND q.response='not_going' AND o.active=true),'[]'::json) not_going_participants FROM games g LEFT JOIN game_fields gf ON gf.id=g.field_id LEFT JOIN game_participants gp ON gp.game_id=g.id AND gp.operator_id=${u.id} WHERE g.game_date>=CURRENT_DATE-interval '1 day' ORDER BY g.game_date,g.game_time NULLS LAST`;const s=await settings();const finance=u.role==='operator'?(await sql`SELECT d.*,to_char(d.period,'YYYY-MM') period_label,s.monthly_fee,s.due_day,s.grace_days,s.currency,s.active finance_active FROM membership_dues d CROSS JOIN finance_settings s WHERE d.operator_id=${u.id} AND d.period=date_trunc('month',CURRENT_DATE)::date LIMIT 1`)[0]||null:null;return json(res,200,{games,finance,financeSettings:s,instagram_url:s.instagram_url||null})}
return json(res,404,{error:'Ação rápida não encontrada.'})}catch(e){console.error('FAST API',e);return json(res,500,{error:e?.message||'Erro interno.'})}}
