import { neon } from '@neondatabase/serverless'
import bcrypt from 'bcryptjs'
import crypto from 'node:crypto'

const sql=neon(process.env.DATABASE_URL)
const COOKIE='tg_session'
const ranks=['Recruta','Soldado','Cabo','3º Sargento','2º Sargento','1º Sargento','Subtenente','Aspirante','Tenente','Capitão','Major','Tenente-Coronel','Coronel']
const json=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store, max-age=0');res.end(JSON.stringify(data))}
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>{const i=v.indexOf('=');return [v.slice(0,i).trim(),decodeURIComponent(v.slice(i+1))]}))
const hash=t=>crypto.createHash('sha256').update(t).digest('hex')
const body=async req=>{let raw='';for await(const c of req)raw+=c;return JSON.parse(raw||'{}')}
const tableCache=new Map()
const columnCache=new Map()
async function hasTable(name){if(tableCache.has(name))return tableCache.get(name);const r=await sql.query("SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name=$1) AS ok",[name]);const ok=!!r.rows?.[0]?.ok;tableCache.set(name,ok);return ok}
async function hasColumn(table,column){const k=table+'.'+column;if(columnCache.has(k))return columnCache.get(k);const r=await sql.query("SELECT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 AND column_name=$2) AS ok",[table,column]);const ok=!!r.rows?.[0]?.ok;columnCache.set(k,ok);return ok}
const value=(o,k,fallback=null)=>o&&o[k]!==undefined?o[k]:fallback
function publicRow(o){return {id:o.id,name:value(o,'name'),nickname:value(o,'nickname'),rank:value(o,'rank','Recruta'),function:value(o,'function','Operador'),games_count:Number(value(o,'games_count',0)||0),absences:Number(value(o,'absences',0)||0),photo_url:value(o,'photo_url'),bio:value(o,'bio',''),equipment_summary:value(o,'equipment_summary',''),elo:value(o,'elo',0),elo_level:Math.min(7,Math.max(1,Number(value(o,'elo_level',7))||7)),age:value(o,'age'),birth_date:value(o,'birth_date'),blood_type:value(o,'blood_type'),airsoft_years:value(o,'airsoft_years'),play_style:value(o,'play_style',''),primary_replica:value(o,'primary_replica',''),secondary_replica:value(o,'secondary_replica','')}}
async function user(req){const token=cookies(req)[COOKIE];if(!token)return null;const r=await sql.query("SELECT o.* FROM sessions s JOIN operators o ON o.id=s.operator_id WHERE s.token_hash=$1 AND s.expires_at>now() AND o.active=true LIMIT 1",[hash(token)]);return r.rows?.[0]||null}
async function requireUser(req,res){const u=await user(req);if(!u){json(res,401,{error:'Faça login.'});return null}return u}
function sessionUser(u){return {id:u.id,name:value(u,'name'),nickname:value(u,'nickname'),email:value(u,'email'),role:value(u,'role','operator'),is_primary_commander:!!value(u,'is_primary_commander',false),rank:value(u,'rank','Recruta'),function:value(u,'function','Operador'),bio:value(u,'bio'),absences:Number(value(u,'absences',0)||0),suspension_until:value(u,'suspension_until'),age:value(u,'age'),blood_type:value(u,'blood_type'),airsoft_years:value(u,'airsoft_years'),play_style:value(u,'play_style',''),primary_replica:value(u,'primary_replica',''),secondary_replica:value(u,'secondary_replica',''),birth_date:value(u,'birth_date'),equipment_summary:value(u,'equipment_summary',''),photo_url:value(u,'photo_url'),public_profile:value(u,'public_profile',true)}}
async function settings(){if(!await hasTable('finance_settings'))return {instagram_url:null,pix_key:null,pix_holder:null,currency:'BRL',monthly_fee:0,due_day:10,grace_days:0,active:true};const r=await sql.query('SELECT * FROM finance_settings WHERE id=1 LIMIT 1');return r.rows?.[0]||{instagram_url:null,pix_key:null,pix_holder:null,currency:'BRL',monthly_fee:0,due_day:10,grace_days:0,active:true}}
async function loadGames(u){if(!await hasTable('games'))return {games:[],finance:null,financeSettings:await settings(),instagram_url:(await settings()).instagram_url||null};const gamesR=await sql.query('SELECT * FROM games WHERE game_date>=CURRENT_DATE-INTERVAL \'1 day\' ORDER BY game_date ASC, game_time NULLS LAST, created_at DESC');const games=gamesR.rows||[];let participants=[];if(await hasTable('game_participants')&&games.length){const ids=games.map(g=>g.id);const p=await sql.query('SELECT * FROM game_participants WHERE game_id = ANY($1::uuid[])',[ids]);participants=p.rows||[]}
const ops=new Map();if(participants.length){const ids=[...new Set(participants.map(p=>p.operator_id))];const q=await sql.query('SELECT * FROM operators WHERE id = ANY($1::uuid[])',[ids]);for(const o of q.rows||[])ops.set(String(o.id),o)}
for(const g of games){g.response='pending';const own=participants.find(p=>String(p.game_id)===String(g.id)&&String(p.operator_id)===String(u.id));if(own)g.response=own.response||((own.attendance===true||String(own.attendance).toLowerCase()==='going')?'going':(own.attendance===false||String(own.attendance).toLowerCase()==='not_going')?'not_going':'pending');g.loadout=own?.loadout||null;g.going_count=0;g.participants=[];g.not_going_participants=[];for(const p of participants.filter(x=>String(x.game_id)===String(g.id))){const o=ops.get(String(p.operator_id));if(!o)continue;const row={id:o.id,nickname:o.nickname,name:o.name,rank:value(o,'rank','Recruta'),function:value(o,'function','Operador'),photo_url:value(o,'photo_url'),elo_level:value(o,'elo_level',7),loadout:p.loadout||{}};const response=p.response||((p.attendance===true||String(p.attendance).toLowerCase()==='going')?'going':(p.attendance===false||String(p.attendance).toLowerCase()==='not_going')?'not_going':'pending');if(response==='going'){g.going_count++;g.participants.push(row)}else if(response==='not_going')g.not_going_participants.push(row)}}
let finance=null;const s=await settings();if(u.role==='operator'&&await hasTable('membership_dues')){const f=await sql.query('SELECT d.*,to_char(d.period,\'YYYY-MM\') AS period_label FROM membership_dues d WHERE d.operator_id=$1 AND d.period=date_trunc(\'month\',CURRENT_DATE)::date LIMIT 1',[u.id]);if(f.rows?.[0])finance={...f.rows[0],monthly_fee:s.monthly_fee,due_day:s.due_day,grace_days:s.grace_days,currency:s.currency,finance_active:s.active}}
return {games,finance,financeSettings:s,instagram_url:s.instagram_url||null,ranks}}
export default async function handler(req,res){try{const url=new URL(req.url,'http://localhost');const action=url.searchParams.get('action')||'me';if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}
if(action==='login'&&req.method==='POST'){const b=await body(req);const identifier=String(b.identifier||'').trim().toLowerCase();const pass=String(b.password||'');let r=await sql.query('SELECT * FROM operators WHERE active=true AND lower(nickname)=lower($1) LIMIT 1',[identifier]);let u=r.rows?.[0];if(!u&&await hasColumn('operators','email')){r=await sql.query('SELECT * FROM operators WHERE active=true AND lower(coalesce(email,\'\'))=$1 LIMIT 1',[identifier]);u=r.rows?.[0]}if(!u||!(await bcrypt.compare(pass,String(u.password_hash||''))))return json(res,401,{error:'E-mail/apelido ou senha inválidos.'});if(u.suspension_until&&new Date(u.suspension_until)>new Date())return json(res,403,{error:`Conta suspensa até ${new Date(u.suspension_until).toLocaleDateString('pt-BR')}.`});const token=crypto.randomBytes(32).toString('hex');await sql.query('INSERT INTO sessions(token_hash,operator_id,expires_at) VALUES($1,$2,now()+interval \'14 days\')',[hash(token),u.id]);res.setHeader('Set-Cookie',`${COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=${60*60*24*14}`);return json(res,200,{user:sessionUser(u)})}
if(action==='me'){const u=await user(req);return json(res,200,{user:u?sessionUser(u):null})}
if(action==='logout'){const token=cookies(req)[COOKIE];if(token)await sql.query('DELETE FROM sessions WHERE token_hash=$1',[hash(token)]);res.setHeader('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0`);return json(res,200,{ok:true})}
if(action==='push-config')return json(res,200,{enabled:!!(process.env.VAPID_PUBLIC_KEY&&process.env.VAPID_PRIVATE_KEY&&process.env.VAPID_SUBJECT),publicKey:process.env.VAPID_PUBLIC_KEY||null})
if(action==='notifications'){const u=await requireUser(req,res);if(!u)return;return json(res,200,{items:await hasTable('notifications')?(await sql.query('SELECT * FROM notifications WHERE operator_id=$1 ORDER BY created_at DESC LIMIT 30',[u.id])).rows:[]})}
if(action==='profile-data'){const u=await requireUser(req,res);if(!u)return;let equipment=[];let gallery=[];if(await hasTable('operator_equipment'))equipment=(await sql.query('SELECT * FROM operator_equipment WHERE operator_id=$1 ORDER BY category,name',[u.id])).rows||[];if(await hasTable('operator_gallery'))gallery=(await sql.query('SELECT * FROM operator_gallery WHERE operator_id=$1 ORDER BY created_at DESC LIMIT 30',[u.id])).rows||[];let guardian=null;let guardianOptions=[];if(await hasColumn('operators','guardian_operator_id')){if(u.guardian_operator_id){const r=await sql.query('SELECT * FROM operators WHERE id=$1 AND active=true LIMIT 1',[u.guardian_operator_id]);guardian=r.rows?.[0]||null}const r=await sql.query('SELECT * FROM operators WHERE active=true AND id<>$1 ORDER BY nickname',[u.id]);guardianOptions=r.rows||[]}return json(res,200,{user:u,equipment,gallery,guardian,guardianOptions})}
if(action==='team-members'){const u=await requireUser(req,res);if(!u)return;const r=await sql.query('SELECT * FROM operators WHERE active=true ORDER BY CASE WHEN role=\'commander\' THEN 0 ELSE 1 END,nickname');const s=await settings();return json(res,200,{operators:(r.rows||[]).map(publicRow),instagram_url:s.instagram_url||null})}
if(action==='games'){const u=await requireUser(req,res);if(!u)return;return json(res,200,await loadGames(u))}
if(action==='public'){const r=await sql.query('SELECT * FROM operators WHERE active=true AND public_profile=true ORDER BY CASE WHEN role=\'commander\' THEN 0 ELSE 1 END,nickname');const s=await settings();let games=[];if(await hasTable('games')){const g=await sql.query('SELECT * FROM games WHERE game_date>=CURRENT_DATE ORDER BY game_date ASC, game_time NULLS LAST, created_at DESC LIMIT 20');games=g.rows||[]}return json(res,200,{operators:(r.rows||[]).map(publicRow),games,completedGames:[],ranks,instagram_url:s.instagram_url||null})}
if(action==='operator'){const id=url.searchParams.get('id');if(!id)return json(res,400,{error:'Operador não informado.'});const r=await sql.query('SELECT * FROM operators WHERE id=$1 AND active=true LIMIT 1',[id]);const o=r.rows?.[0];if(!o)return json(res,404,{error:'Operador não encontrado.'});let equipment=[];let gallery=[];if(await hasTable('operator_equipment'))equipment=(await sql.query('SELECT * FROM operator_equipment WHERE operator_id=$1 AND public_visible=true ORDER BY category,name',[id])).rows||[];if(await hasTable('operator_gallery'))gallery=(await sql.query('SELECT * FROM operator_gallery WHERE operator_id=$1 ORDER BY created_at DESC LIMIT 18',[id])).rows||[];return json(res,200,{operator:publicRow(o),equipment,gallery})}
return json(res,404,{error:'Ação não encontrada.'})}catch(e){console.error('OPERATOR SAFE API',e);return json(res,500,{error:e?.message||'Erro interno.'})}}