import { neon } from '@neondatabase/serverless'
import crypto from 'node:crypto'
const sql=neon(process.env.DATABASE_URL);const COOKIE='tg_session';
const json=(res,s,d)=>{res.statusCode=s;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store,max-age=0');res.end(JSON.stringify(d))};
const hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>{const i=v.indexOf('=');return [v.slice(0,i).trim(),decodeURIComponent(v.slice(i+1))]}));
async function auth(req,res,commander=false){const t=cookies(req)[COOKIE];if(!t){json(res,401,{error:'Faça login.'});return null}const r=await sql`SELECT o.* FROM sessions s JOIN operators o ON o.id=s.operator_id WHERE s.token_hash=${hash(t)} AND s.expires_at>now() AND o.active=true LIMIT 1`;const u=r[0];if(!u){json(res,401,{error:'Sessão expirada.'});return null}if(commander&&u.role!=='commander'){json(res,403,{error:'Acesso restrito ao comandante.'});return null}return u}
const op=o=>({id:o.id,name:o.name,nickname:o.nickname,rank:o.rank,function:o.function||'Operador',photo_url:o.photo_url||null,bio:o.bio||'',elo_level:o.elo_level||7,airsoft_years:o.airsoft_years||null,play_style:o.play_style||'',primary_replica:o.primary_replica||'',secondary_replica:o.secondary_replica||''});
export default async function handler(req,res){try{const uurl=new URL(req.url,'http://localhost');const action=uurl.searchParams.get('action')||'';
if(action==='team'){const u=await auth(req,res);if(!u)return;const rows=await sql`SELECT * FROM operators WHERE active=true ORDER BY CASE WHEN role='commander' THEN 0 ELSE 1 END,nickname`;return json(res,200,{operators:rows.map(op)})}
if(action==='profile'){const u=await auth(req,res);if(!u)return;const id=uurl.searchParams.get('id');const o=(await sql`SELECT * FROM operators WHERE id=${id} AND active=true LIMIT 1`)[0];if(!o)return json(res,404,{error:'Operador não encontrado.'});const equipment=await sql`SELECT id,category,name,details,photo_url FROM operator_equipment WHERE operator_id=${id} ORDER BY category,name`;const gallery=await sql`SELECT id,image_data,caption FROM operator_gallery WHERE operator_id=${id} ORDER BY created_at DESC LIMIT 18`;return json(res,200,{operator:op(o),equipment,gallery})}
if(action==='roster'){const u=await auth(req,res);if(!u)return;const games=await sql`SELECT id,title,game_date,game_time,status FROM games WHERE game_date>=CURRENT_DATE-interval '1 day' AND COALESCE(status,'')<>'cancelado' ORDER BY game_date,game_time NULLS LAST`;const ops=await sql`SELECT id,name,nickname,rank,function,photo_url,elo_level FROM operators WHERE active=true ORDER BY nickname`;const out=[];for(const g of games){const rows=await sql`SELECT operator_id,response FROM game_participants WHERE game_id=${g.id}`;const map=new Map(rows.map(x=>[String(x.operator_id),x.response]));const going=[],not_going=[],pending=[];for(const o of ops){const x=op(o),r=map.get(String(o.id))||'pending';(r==='going'?going:r==='not_going'?not_going:pending).push(x)}out.push({...g,going,not_going,pending})}return json(res,200,{games:out})}
if(action==='history'){const u=await auth(req,res,true);if(!u)return;const games=await sql`SELECT id,title,game_date,game_time,location,status,match_photo_url,completed_at FROM games WHERE status='finalizado' OR completed_at IS NOT NULL ORDER BY COALESCE(completed_at,game_date::timestamptz) DESC LIMIT 100`;return json(res,200,{games})}
if(action==='finance'){const u=await auth(req,res,true);if(!u)return;const settings=(await sql`SELECT * FROM finance_settings WHERE id=1 LIMIT 1`)[0]||{};const tx=await sql`SELECT * FROM finance_transactions ORDER BY transaction_date DESC,created_at DESC LIMIT 150`;const dues=await sql`SELECT d.*,o.nickname,o.rank FROM membership_dues d JOIN operators o ON o.id=d.operator_id ORDER BY d.period DESC,o.nickname LIMIT 250`;return json(res,200,{settings,transactions:tx,dues})}
return json(res,404,{error:'Ação não encontrada.'})}catch(e){console.error('PANEL LITE',e);return json(res,500,{error:e?.message||'Erro interno.'})}}
